// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: RawTrace.proto

#ifndef PROTOBUF_INCLUDED_RawTrace_2eproto
#define PROTOBUF_INCLUDED_RawTrace_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3007000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3007001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_RawTrace_2eproto

// Internal implementation detail -- do not use these members.
struct TableStruct_RawTrace_2eproto {
  static const ::google::protobuf::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::ParseTable schema[7]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors_RawTrace_2eproto();
namespace RawTrace {
class Data;
class DataDefaultTypeInternal;
extern DataDefaultTypeInternal _Data_default_instance_;
class Ins;
class InsDefaultTypeInternal;
extern InsDefaultTypeInternal _Ins_default_instance_;
class Mem;
class MemDefaultTypeInternal;
extern MemDefaultTypeInternal _Mem_default_instance_;
class Record;
class RecordDefaultTypeInternal;
extern RecordDefaultTypeInternal _Record_default_instance_;
class Sched;
class SchedDefaultTypeInternal;
extern SchedDefaultTypeInternal _Sched_default_instance_;
class Syscall;
class SyscallDefaultTypeInternal;
extern SyscallDefaultTypeInternal _Syscall_default_instance_;
class Trace;
class TraceDefaultTypeInternal;
extern TraceDefaultTypeInternal _Trace_default_instance_;
}  // namespace RawTrace
namespace google {
namespace protobuf {
template<> ::RawTrace::Data* Arena::CreateMaybeMessage<::RawTrace::Data>(Arena*);
template<> ::RawTrace::Ins* Arena::CreateMaybeMessage<::RawTrace::Ins>(Arena*);
template<> ::RawTrace::Mem* Arena::CreateMaybeMessage<::RawTrace::Mem>(Arena*);
template<> ::RawTrace::Record* Arena::CreateMaybeMessage<::RawTrace::Record>(Arena*);
template<> ::RawTrace::Sched* Arena::CreateMaybeMessage<::RawTrace::Sched>(Arena*);
template<> ::RawTrace::Syscall* Arena::CreateMaybeMessage<::RawTrace::Syscall>(Arena*);
template<> ::RawTrace::Trace* Arena::CreateMaybeMessage<::RawTrace::Trace>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace RawTrace {

enum DataType {
  EXPORT_INVALID = 0,
  EXPORT_KMEM_CACHE_OBJECT_SIZE = 1,
  EXPORT_KMEM_CACHE_OBJECT_PTR = 2,
  DataType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  DataType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool DataType_IsValid(int value);
const DataType DataType_MIN = EXPORT_INVALID;
const DataType DataType_MAX = EXPORT_KMEM_CACHE_OBJECT_PTR;
const int DataType_ARRAYSIZE = DataType_MAX + 1;

const ::google::protobuf::EnumDescriptor* DataType_descriptor();
inline const ::std::string& DataType_Name(DataType value) {
  return ::google::protobuf::internal::NameOfEnum(
    DataType_descriptor(), value);
}
inline bool DataType_Parse(
    const ::std::string& name, DataType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<DataType>(
    DataType_descriptor(), name, value);
}
enum SchedType {
  SCHED_INVALID = 0,
  SCHED_THREAD_CREATE = 1,
  SCHED_THREAD_OUT = 2,
  SCHED_THREAD_IN = 3,
  SCHED_THREAD_EXIT = 4,
  SCHED_SOFTIRQ_CREATE = 5,
  SCHED_SOFTIRQ_OUT = 6,
  SCHED_SOFTIRQ_IN = 7,
  SCHED_WORK_CREATE = 8,
  SCHED_WORK_OUT = 9,
  SCHED_WORK_IN = 10,
  SchedType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::min(),
  SchedType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::google::protobuf::int32>::max()
};
bool SchedType_IsValid(int value);
const SchedType SchedType_MIN = SCHED_INVALID;
const SchedType SchedType_MAX = SCHED_WORK_IN;
const int SchedType_ARRAYSIZE = SchedType_MAX + 1;

const ::google::protobuf::EnumDescriptor* SchedType_descriptor();
inline const ::std::string& SchedType_Name(SchedType value) {
  return ::google::protobuf::internal::NameOfEnum(
    SchedType_descriptor(), value);
}
inline bool SchedType_Parse(
    const ::std::string& name, SchedType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SchedType>(
    SchedType_descriptor(), name, value);
}
// ===================================================================

class Syscall :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RawTrace.Syscall) */ {
 public:
  Syscall();
  virtual ~Syscall();

  Syscall(const Syscall& from);

  inline Syscall& operator=(const Syscall& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Syscall(Syscall&& from) noexcept
    : Syscall() {
    *this = ::std::move(from);
  }

  inline Syscall& operator=(Syscall&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Syscall& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Syscall* internal_default_instance() {
    return reinterpret_cast<const Syscall*>(
               &_Syscall_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Syscall* other);
  friend void swap(Syscall& a, Syscall& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Syscall* New() const final {
    return CreateMaybeMessage<Syscall>(nullptr);
  }

  Syscall* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Syscall>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Syscall& from);
  void MergeFrom(const Syscall& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Syscall* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string arg_names = 5;
  int arg_names_size() const;
  void clear_arg_names();
  static const int kArgNamesFieldNumber = 5;
  const ::std::string& arg_names(int index) const;
  ::std::string* mutable_arg_names(int index);
  void set_arg_names(int index, const ::std::string& value);
  #if LANG_CXX11
  void set_arg_names(int index, ::std::string&& value);
  #endif
  void set_arg_names(int index, const char* value);
  void set_arg_names(int index, const char* value, size_t size);
  ::std::string* add_arg_names();
  void add_arg_names(const ::std::string& value);
  #if LANG_CXX11
  void add_arg_names(::std::string&& value);
  #endif
  void add_arg_names(const char* value);
  void add_arg_names(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField<::std::string>& arg_names() const;
  ::google::protobuf::RepeatedPtrField<::std::string>* mutable_arg_names();

  // repeated uint64 arg_values = 6;
  int arg_values_size() const;
  void clear_arg_values();
  static const int kArgValuesFieldNumber = 6;
  ::google::protobuf::uint64 arg_values(int index) const;
  void set_arg_values(int index, ::google::protobuf::uint64 value);
  void add_arg_values(::google::protobuf::uint64 value);
  const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
      arg_values() const;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
      mutable_arg_values();

  // string name = 3;
  void clear_name();
  static const int kNameFieldNumber = 3;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // uint64 num = 1;
  void clear_num();
  static const int kNumFieldNumber = 1;
  ::google::protobuf::uint64 num() const;
  void set_num(::google::protobuf::uint64 value);

  // uint32 id = 2;
  void clear_id();
  static const int kIdFieldNumber = 2;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // uint32 nr_args = 4;
  void clear_nr_args();
  static const int kNrArgsFieldNumber = 4;
  ::google::protobuf::uint32 nr_args() const;
  void set_nr_args(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:RawTrace.Syscall)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField<::std::string> arg_names_;
  ::google::protobuf::RepeatedField< ::google::protobuf::uint64 > arg_values_;
  mutable std::atomic<int> _arg_values_cached_byte_size_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint64 num_;
  ::google::protobuf::uint32 id_;
  ::google::protobuf::uint32 nr_args_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_RawTrace_2eproto;
};
// -------------------------------------------------------------------

class Mem :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RawTrace.Mem) */ {
 public:
  Mem();
  virtual ~Mem();

  Mem(const Mem& from);

  inline Mem& operator=(const Mem& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Mem(Mem&& from) noexcept
    : Mem() {
    *this = ::std::move(from);
  }

  inline Mem& operator=(Mem&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Mem& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Mem* internal_default_instance() {
    return reinterpret_cast<const Mem*>(
               &_Mem_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  void Swap(Mem* other);
  friend void swap(Mem& a, Mem& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Mem* New() const final {
    return CreateMaybeMessage<Mem>(nullptr);
  }

  Mem* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Mem>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Mem& from);
  void MergeFrom(const Mem& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Mem* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 addr = 1;
  void clear_addr();
  static const int kAddrFieldNumber = 1;
  ::google::protobuf::uint64 addr() const;
  void set_addr(::google::protobuf::uint64 value);

  // uint64 value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::google::protobuf::uint64 value() const;
  void set_value(::google::protobuf::uint64 value);

  // uint64 ip = 3;
  void clear_ip();
  static const int kIpFieldNumber = 3;
  ::google::protobuf::uint64 ip() const;
  void set_ip(::google::protobuf::uint64 value);

  // uint32 size = 4;
  void clear_size();
  static const int kSizeFieldNumber = 4;
  ::google::protobuf::uint32 size() const;
  void set_size(::google::protobuf::uint32 value);

  // uint32 pid = 5;
  void clear_pid();
  static const int kPidFieldNumber = 5;
  ::google::protobuf::uint32 pid() const;
  void set_pid(::google::protobuf::uint32 value);

  // bool is_write = 6;
  void clear_is_write();
  static const int kIsWriteFieldNumber = 6;
  bool is_write() const;
  void set_is_write(bool value);

  // @@protoc_insertion_point(class_scope:RawTrace.Mem)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 addr_;
  ::google::protobuf::uint64 value_;
  ::google::protobuf::uint64 ip_;
  ::google::protobuf::uint32 size_;
  ::google::protobuf::uint32 pid_;
  bool is_write_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_RawTrace_2eproto;
};
// -------------------------------------------------------------------

class Ins :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RawTrace.Ins) */ {
 public:
  Ins();
  virtual ~Ins();

  Ins(const Ins& from);

  inline Ins& operator=(const Ins& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Ins(Ins&& from) noexcept
    : Ins() {
    *this = ::std::move(from);
  }

  inline Ins& operator=(Ins&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Ins& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Ins* internal_default_instance() {
    return reinterpret_cast<const Ins*>(
               &_Ins_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  void Swap(Ins* other);
  friend void swap(Ins& a, Ins& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Ins* New() const final {
    return CreateMaybeMessage<Ins>(nullptr);
  }

  Ins* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Ins>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Ins& from);
  void MergeFrom(const Ins& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Ins* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 num = 1;
  void clear_num();
  static const int kNumFieldNumber = 1;
  ::google::protobuf::uint64 num() const;
  void set_num(::google::protobuf::uint64 value);

  // uint64 pc = 2;
  void clear_pc();
  static const int kPcFieldNumber = 2;
  ::google::protobuf::uint64 pc() const;
  void set_pc(::google::protobuf::uint64 value);

  // uint64 rax = 3;
  void clear_rax();
  static const int kRaxFieldNumber = 3;
  ::google::protobuf::uint64 rax() const;
  void set_rax(::google::protobuf::uint64 value);

  // uint64 rcx = 4;
  void clear_rcx();
  static const int kRcxFieldNumber = 4;
  ::google::protobuf::uint64 rcx() const;
  void set_rcx(::google::protobuf::uint64 value);

  // uint64 rdx = 5;
  void clear_rdx();
  static const int kRdxFieldNumber = 5;
  ::google::protobuf::uint64 rdx() const;
  void set_rdx(::google::protobuf::uint64 value);

  // uint64 rbx = 6;
  void clear_rbx();
  static const int kRbxFieldNumber = 6;
  ::google::protobuf::uint64 rbx() const;
  void set_rbx(::google::protobuf::uint64 value);

  // uint64 rsp = 7;
  void clear_rsp();
  static const int kRspFieldNumber = 7;
  ::google::protobuf::uint64 rsp() const;
  void set_rsp(::google::protobuf::uint64 value);

  // uint64 rbp = 8;
  void clear_rbp();
  static const int kRbpFieldNumber = 8;
  ::google::protobuf::uint64 rbp() const;
  void set_rbp(::google::protobuf::uint64 value);

  // uint64 rsi = 9;
  void clear_rsi();
  static const int kRsiFieldNumber = 9;
  ::google::protobuf::uint64 rsi() const;
  void set_rsi(::google::protobuf::uint64 value);

  // uint64 rdi = 10;
  void clear_rdi();
  static const int kRdiFieldNumber = 10;
  ::google::protobuf::uint64 rdi() const;
  void set_rdi(::google::protobuf::uint64 value);

  // uint64 r8 = 11;
  void clear_r8();
  static const int kR8FieldNumber = 11;
  ::google::protobuf::uint64 r8() const;
  void set_r8(::google::protobuf::uint64 value);

  // uint64 r9 = 12;
  void clear_r9();
  static const int kR9FieldNumber = 12;
  ::google::protobuf::uint64 r9() const;
  void set_r9(::google::protobuf::uint64 value);

  // uint64 r10 = 13;
  void clear_r10();
  static const int kR10FieldNumber = 13;
  ::google::protobuf::uint64 r10() const;
  void set_r10(::google::protobuf::uint64 value);

  // uint64 r11 = 14;
  void clear_r11();
  static const int kR11FieldNumber = 14;
  ::google::protobuf::uint64 r11() const;
  void set_r11(::google::protobuf::uint64 value);

  // uint64 r12 = 15;
  void clear_r12();
  static const int kR12FieldNumber = 15;
  ::google::protobuf::uint64 r12() const;
  void set_r12(::google::protobuf::uint64 value);

  // uint64 r13 = 16;
  void clear_r13();
  static const int kR13FieldNumber = 16;
  ::google::protobuf::uint64 r13() const;
  void set_r13(::google::protobuf::uint64 value);

  // uint64 r14 = 17;
  void clear_r14();
  static const int kR14FieldNumber = 17;
  ::google::protobuf::uint64 r14() const;
  void set_r14(::google::protobuf::uint64 value);

  // uint64 r15 = 18;
  void clear_r15();
  static const int kR15FieldNumber = 18;
  ::google::protobuf::uint64 r15() const;
  void set_r15(::google::protobuf::uint64 value);

  // uint64 cc_op = 19;
  void clear_cc_op();
  static const int kCcOpFieldNumber = 19;
  ::google::protobuf::uint64 cc_op() const;
  void set_cc_op(::google::protobuf::uint64 value);

  // uint64 cc_dep1 = 20;
  void clear_cc_dep1();
  static const int kCcDep1FieldNumber = 20;
  ::google::protobuf::uint64 cc_dep1() const;
  void set_cc_dep1(::google::protobuf::uint64 value);

  // uint64 cc_dep2 = 21;
  void clear_cc_dep2();
  static const int kCcDep2FieldNumber = 21;
  ::google::protobuf::uint64 cc_dep2() const;
  void set_cc_dep2(::google::protobuf::uint64 value);

  // uint64 cc_ndep = 22;
  void clear_cc_ndep();
  static const int kCcNdepFieldNumber = 22;
  ::google::protobuf::uint64 cc_ndep() const;
  void set_cc_ndep(::google::protobuf::uint64 value);

  // uint64 gs = 23;
  void clear_gs();
  static const int kGsFieldNumber = 23;
  ::google::protobuf::uint64 gs() const;
  void set_gs(::google::protobuf::uint64 value);

  // uint64 r_184 = 24;
  void clear_r_184();
  static const int kR184FieldNumber = 24;
  ::google::protobuf::uint64 r_184() const;
  void set_r_184(::google::protobuf::uint64 value);

  // uint64 r_192 = 25;
  void clear_r_192();
  static const int kR192FieldNumber = 25;
  ::google::protobuf::uint64 r_192() const;
  void set_r_192(::google::protobuf::uint64 value);

  // uint64 r_200 = 26;
  void clear_r_200();
  static const int kR200FieldNumber = 26;
  ::google::protobuf::uint64 r_200() const;
  void set_r_200(::google::protobuf::uint64 value);

  // uint64 pid = 27;
  void clear_pid();
  static const int kPidFieldNumber = 27;
  ::google::protobuf::uint64 pid() const;
  void set_pid(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:RawTrace.Ins)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 num_;
  ::google::protobuf::uint64 pc_;
  ::google::protobuf::uint64 rax_;
  ::google::protobuf::uint64 rcx_;
  ::google::protobuf::uint64 rdx_;
  ::google::protobuf::uint64 rbx_;
  ::google::protobuf::uint64 rsp_;
  ::google::protobuf::uint64 rbp_;
  ::google::protobuf::uint64 rsi_;
  ::google::protobuf::uint64 rdi_;
  ::google::protobuf::uint64 r8_;
  ::google::protobuf::uint64 r9_;
  ::google::protobuf::uint64 r10_;
  ::google::protobuf::uint64 r11_;
  ::google::protobuf::uint64 r12_;
  ::google::protobuf::uint64 r13_;
  ::google::protobuf::uint64 r14_;
  ::google::protobuf::uint64 r15_;
  ::google::protobuf::uint64 cc_op_;
  ::google::protobuf::uint64 cc_dep1_;
  ::google::protobuf::uint64 cc_dep2_;
  ::google::protobuf::uint64 cc_ndep_;
  ::google::protobuf::uint64 gs_;
  ::google::protobuf::uint64 r_184_;
  ::google::protobuf::uint64 r_192_;
  ::google::protobuf::uint64 r_200_;
  ::google::protobuf::uint64 pid_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_RawTrace_2eproto;
};
// -------------------------------------------------------------------

class Data :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RawTrace.Data) */ {
 public:
  Data();
  virtual ~Data();

  Data(const Data& from);

  inline Data& operator=(const Data& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Data(Data&& from) noexcept
    : Data() {
    *this = ::std::move(from);
  }

  inline Data& operator=(Data&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Data& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Data* internal_default_instance() {
    return reinterpret_cast<const Data*>(
               &_Data_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  void Swap(Data* other);
  friend void swap(Data& a, Data& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Data* New() const final {
    return CreateMaybeMessage<Data>(nullptr);
  }

  Data* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Data>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Data& from);
  void MergeFrom(const Data& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Data* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // uint64 value = 2;
  void clear_value();
  static const int kValueFieldNumber = 2;
  ::google::protobuf::uint64 value() const;
  void set_value(::google::protobuf::uint64 value);

  // .RawTrace.DataType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::RawTrace::DataType type() const;
  void set_type(::RawTrace::DataType value);

  // @@protoc_insertion_point(class_scope:RawTrace.Data)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint64 value_;
  int type_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_RawTrace_2eproto;
};
// -------------------------------------------------------------------

class Sched :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RawTrace.Sched) */ {
 public:
  Sched();
  virtual ~Sched();

  Sched(const Sched& from);

  inline Sched& operator=(const Sched& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Sched(Sched&& from) noexcept
    : Sched() {
    *this = ::std::move(from);
  }

  inline Sched& operator=(Sched&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Sched& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Sched* internal_default_instance() {
    return reinterpret_cast<const Sched*>(
               &_Sched_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  void Swap(Sched* other);
  friend void swap(Sched& a, Sched& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Sched* New() const final {
    return CreateMaybeMessage<Sched>(nullptr);
  }

  Sched* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Sched>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Sched& from);
  void MergeFrom(const Sched& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Sched* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .RawTrace.SchedType type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::RawTrace::SchedType type() const;
  void set_type(::RawTrace::SchedType value);

  // uint32 pid = 2;
  void clear_pid();
  static const int kPidFieldNumber = 2;
  ::google::protobuf::uint32 pid() const;
  void set_pid(::google::protobuf::uint32 value);

  // uint64 target = 3;
  void clear_target();
  static const int kTargetFieldNumber = 3;
  ::google::protobuf::uint64 target() const;
  void set_target(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:RawTrace.Sched)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  int type_;
  ::google::protobuf::uint32 pid_;
  ::google::protobuf::uint64 target_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_RawTrace_2eproto;
};
// -------------------------------------------------------------------

class Record :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RawTrace.Record) */ {
 public:
  Record();
  virtual ~Record();

  Record(const Record& from);

  inline Record& operator=(const Record& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Record(Record&& from) noexcept
    : Record() {
    *this = ::std::move(from);
  }

  inline Record& operator=(Record&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Record& default_instance();

  enum ItemCase {
    kIns = 1,
    kMem = 2,
    kData = 3,
    kSyscall = 4,
    kSched = 5,
    ITEM_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Record* internal_default_instance() {
    return reinterpret_cast<const Record*>(
               &_Record_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  void Swap(Record* other);
  friend void swap(Record& a, Record& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Record* New() const final {
    return CreateMaybeMessage<Record>(nullptr);
  }

  Record* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Record>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Record& from);
  void MergeFrom(const Record& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Record* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .RawTrace.Ins ins = 1;
  bool has_ins() const;
  void clear_ins();
  static const int kInsFieldNumber = 1;
  const ::RawTrace::Ins& ins() const;
  ::RawTrace::Ins* release_ins();
  ::RawTrace::Ins* mutable_ins();
  void set_allocated_ins(::RawTrace::Ins* ins);

  // .RawTrace.Mem mem = 2;
  bool has_mem() const;
  void clear_mem();
  static const int kMemFieldNumber = 2;
  const ::RawTrace::Mem& mem() const;
  ::RawTrace::Mem* release_mem();
  ::RawTrace::Mem* mutable_mem();
  void set_allocated_mem(::RawTrace::Mem* mem);

  // .RawTrace.Data data = 3;
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 3;
  const ::RawTrace::Data& data() const;
  ::RawTrace::Data* release_data();
  ::RawTrace::Data* mutable_data();
  void set_allocated_data(::RawTrace::Data* data);

  // .RawTrace.Syscall syscall = 4;
  bool has_syscall() const;
  void clear_syscall();
  static const int kSyscallFieldNumber = 4;
  const ::RawTrace::Syscall& syscall() const;
  ::RawTrace::Syscall* release_syscall();
  ::RawTrace::Syscall* mutable_syscall();
  void set_allocated_syscall(::RawTrace::Syscall* syscall);

  // .RawTrace.Sched sched = 5;
  bool has_sched() const;
  void clear_sched();
  static const int kSchedFieldNumber = 5;
  const ::RawTrace::Sched& sched() const;
  ::RawTrace::Sched* release_sched();
  ::RawTrace::Sched* mutable_sched();
  void set_allocated_sched(::RawTrace::Sched* sched);

  void clear_item();
  ItemCase item_case() const;
  // @@protoc_insertion_point(class_scope:RawTrace.Record)
 private:
  class HasBitSetters;
  void set_has_ins();
  void set_has_mem();
  void set_has_data();
  void set_has_syscall();
  void set_has_sched();

  inline bool has_item() const;
  inline void clear_has_item();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  union ItemUnion {
    ItemUnion() {}
    ::RawTrace::Ins* ins_;
    ::RawTrace::Mem* mem_;
    ::RawTrace::Data* data_;
    ::RawTrace::Syscall* syscall_;
    ::RawTrace::Sched* sched_;
  } item_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::TableStruct_RawTrace_2eproto;
};
// -------------------------------------------------------------------

class Trace :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:RawTrace.Trace) */ {
 public:
  Trace();
  virtual ~Trace();

  Trace(const Trace& from);

  inline Trace& operator=(const Trace& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Trace(Trace&& from) noexcept
    : Trace() {
    *this = ::std::move(from);
  }

  inline Trace& operator=(Trace&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor() {
    return default_instance().GetDescriptor();
  }
  static const Trace& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Trace* internal_default_instance() {
    return reinterpret_cast<const Trace*>(
               &_Trace_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  void Swap(Trace* other);
  friend void swap(Trace& a, Trace& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Trace* New() const final {
    return CreateMaybeMessage<Trace>(nullptr);
  }

  Trace* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Trace>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Trace& from);
  void MergeFrom(const Trace& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  #if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  static const char* _InternalParse(const char* begin, const char* end, void* object, ::google::protobuf::internal::ParseContext* ctx);
  ::google::protobuf::internal::ParseFunc _ParseFunc() const final { return _InternalParse; }
  #else
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  #endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Trace* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .RawTrace.Record records = 1;
  int records_size() const;
  void clear_records();
  static const int kRecordsFieldNumber = 1;
  ::RawTrace::Record* mutable_records(int index);
  ::google::protobuf::RepeatedPtrField< ::RawTrace::Record >*
      mutable_records();
  const ::RawTrace::Record& records(int index) const;
  ::RawTrace::Record* add_records();
  const ::google::protobuf::RepeatedPtrField< ::RawTrace::Record >&
      records() const;

  // @@protoc_insertion_point(class_scope:RawTrace.Trace)
 private:
  class HasBitSetters;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::RawTrace::Record > records_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_RawTrace_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Syscall

// uint64 num = 1;
inline void Syscall::clear_num() {
  num_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Syscall::num() const {
  // @@protoc_insertion_point(field_get:RawTrace.Syscall.num)
  return num_;
}
inline void Syscall::set_num(::google::protobuf::uint64 value) {
  
  num_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Syscall.num)
}

// uint32 id = 2;
inline void Syscall::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 Syscall::id() const {
  // @@protoc_insertion_point(field_get:RawTrace.Syscall.id)
  return id_;
}
inline void Syscall::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Syscall.id)
}

// string name = 3;
inline void Syscall::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& Syscall::name() const {
  // @@protoc_insertion_point(field_get:RawTrace.Syscall.name)
  return name_.GetNoArena();
}
inline void Syscall::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:RawTrace.Syscall.name)
}
#if LANG_CXX11
inline void Syscall::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:RawTrace.Syscall.name)
}
#endif
inline void Syscall::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:RawTrace.Syscall.name)
}
inline void Syscall::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:RawTrace.Syscall.name)
}
inline ::std::string* Syscall::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:RawTrace.Syscall.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Syscall::release_name() {
  // @@protoc_insertion_point(field_release:RawTrace.Syscall.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Syscall::set_allocated_name(::std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:RawTrace.Syscall.name)
}

// uint32 nr_args = 4;
inline void Syscall::clear_nr_args() {
  nr_args_ = 0u;
}
inline ::google::protobuf::uint32 Syscall::nr_args() const {
  // @@protoc_insertion_point(field_get:RawTrace.Syscall.nr_args)
  return nr_args_;
}
inline void Syscall::set_nr_args(::google::protobuf::uint32 value) {
  
  nr_args_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Syscall.nr_args)
}

// repeated string arg_names = 5;
inline int Syscall::arg_names_size() const {
  return arg_names_.size();
}
inline void Syscall::clear_arg_names() {
  arg_names_.Clear();
}
inline const ::std::string& Syscall::arg_names(int index) const {
  // @@protoc_insertion_point(field_get:RawTrace.Syscall.arg_names)
  return arg_names_.Get(index);
}
inline ::std::string* Syscall::mutable_arg_names(int index) {
  // @@protoc_insertion_point(field_mutable:RawTrace.Syscall.arg_names)
  return arg_names_.Mutable(index);
}
inline void Syscall::set_arg_names(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:RawTrace.Syscall.arg_names)
  arg_names_.Mutable(index)->assign(value);
}
#if LANG_CXX11
inline void Syscall::set_arg_names(int index, ::std::string&& value) {
  // @@protoc_insertion_point(field_set:RawTrace.Syscall.arg_names)
  arg_names_.Mutable(index)->assign(std::move(value));
}
#endif
inline void Syscall::set_arg_names(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  arg_names_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:RawTrace.Syscall.arg_names)
}
inline void Syscall::set_arg_names(int index, const char* value, size_t size) {
  arg_names_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:RawTrace.Syscall.arg_names)
}
inline ::std::string* Syscall::add_arg_names() {
  // @@protoc_insertion_point(field_add_mutable:RawTrace.Syscall.arg_names)
  return arg_names_.Add();
}
inline void Syscall::add_arg_names(const ::std::string& value) {
  arg_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:RawTrace.Syscall.arg_names)
}
#if LANG_CXX11
inline void Syscall::add_arg_names(::std::string&& value) {
  arg_names_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:RawTrace.Syscall.arg_names)
}
#endif
inline void Syscall::add_arg_names(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  arg_names_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:RawTrace.Syscall.arg_names)
}
inline void Syscall::add_arg_names(const char* value, size_t size) {
  arg_names_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:RawTrace.Syscall.arg_names)
}
inline const ::google::protobuf::RepeatedPtrField<::std::string>&
Syscall::arg_names() const {
  // @@protoc_insertion_point(field_list:RawTrace.Syscall.arg_names)
  return arg_names_;
}
inline ::google::protobuf::RepeatedPtrField<::std::string>*
Syscall::mutable_arg_names() {
  // @@protoc_insertion_point(field_mutable_list:RawTrace.Syscall.arg_names)
  return &arg_names_;
}

// repeated uint64 arg_values = 6;
inline int Syscall::arg_values_size() const {
  return arg_values_.size();
}
inline void Syscall::clear_arg_values() {
  arg_values_.Clear();
}
inline ::google::protobuf::uint64 Syscall::arg_values(int index) const {
  // @@protoc_insertion_point(field_get:RawTrace.Syscall.arg_values)
  return arg_values_.Get(index);
}
inline void Syscall::set_arg_values(int index, ::google::protobuf::uint64 value) {
  arg_values_.Set(index, value);
  // @@protoc_insertion_point(field_set:RawTrace.Syscall.arg_values)
}
inline void Syscall::add_arg_values(::google::protobuf::uint64 value) {
  arg_values_.Add(value);
  // @@protoc_insertion_point(field_add:RawTrace.Syscall.arg_values)
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >&
Syscall::arg_values() const {
  // @@protoc_insertion_point(field_list:RawTrace.Syscall.arg_values)
  return arg_values_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::uint64 >*
Syscall::mutable_arg_values() {
  // @@protoc_insertion_point(field_mutable_list:RawTrace.Syscall.arg_values)
  return &arg_values_;
}

// -------------------------------------------------------------------

// Mem

// uint64 addr = 1;
inline void Mem::clear_addr() {
  addr_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Mem::addr() const {
  // @@protoc_insertion_point(field_get:RawTrace.Mem.addr)
  return addr_;
}
inline void Mem::set_addr(::google::protobuf::uint64 value) {
  
  addr_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Mem.addr)
}

// uint64 value = 2;
inline void Mem::clear_value() {
  value_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Mem::value() const {
  // @@protoc_insertion_point(field_get:RawTrace.Mem.value)
  return value_;
}
inline void Mem::set_value(::google::protobuf::uint64 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Mem.value)
}

// uint64 ip = 3;
inline void Mem::clear_ip() {
  ip_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Mem::ip() const {
  // @@protoc_insertion_point(field_get:RawTrace.Mem.ip)
  return ip_;
}
inline void Mem::set_ip(::google::protobuf::uint64 value) {
  
  ip_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Mem.ip)
}

// uint32 size = 4;
inline void Mem::clear_size() {
  size_ = 0u;
}
inline ::google::protobuf::uint32 Mem::size() const {
  // @@protoc_insertion_point(field_get:RawTrace.Mem.size)
  return size_;
}
inline void Mem::set_size(::google::protobuf::uint32 value) {
  
  size_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Mem.size)
}

// uint32 pid = 5;
inline void Mem::clear_pid() {
  pid_ = 0u;
}
inline ::google::protobuf::uint32 Mem::pid() const {
  // @@protoc_insertion_point(field_get:RawTrace.Mem.pid)
  return pid_;
}
inline void Mem::set_pid(::google::protobuf::uint32 value) {
  
  pid_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Mem.pid)
}

// bool is_write = 6;
inline void Mem::clear_is_write() {
  is_write_ = false;
}
inline bool Mem::is_write() const {
  // @@protoc_insertion_point(field_get:RawTrace.Mem.is_write)
  return is_write_;
}
inline void Mem::set_is_write(bool value) {
  
  is_write_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Mem.is_write)
}

// -------------------------------------------------------------------

// Ins

// uint64 num = 1;
inline void Ins::clear_num() {
  num_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::num() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.num)
  return num_;
}
inline void Ins::set_num(::google::protobuf::uint64 value) {
  
  num_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.num)
}

// uint64 pc = 2;
inline void Ins::clear_pc() {
  pc_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::pc() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.pc)
  return pc_;
}
inline void Ins::set_pc(::google::protobuf::uint64 value) {
  
  pc_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.pc)
}

// uint64 rax = 3;
inline void Ins::clear_rax() {
  rax_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::rax() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.rax)
  return rax_;
}
inline void Ins::set_rax(::google::protobuf::uint64 value) {
  
  rax_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.rax)
}

// uint64 rcx = 4;
inline void Ins::clear_rcx() {
  rcx_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::rcx() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.rcx)
  return rcx_;
}
inline void Ins::set_rcx(::google::protobuf::uint64 value) {
  
  rcx_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.rcx)
}

// uint64 rdx = 5;
inline void Ins::clear_rdx() {
  rdx_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::rdx() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.rdx)
  return rdx_;
}
inline void Ins::set_rdx(::google::protobuf::uint64 value) {
  
  rdx_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.rdx)
}

// uint64 rbx = 6;
inline void Ins::clear_rbx() {
  rbx_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::rbx() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.rbx)
  return rbx_;
}
inline void Ins::set_rbx(::google::protobuf::uint64 value) {
  
  rbx_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.rbx)
}

// uint64 rsp = 7;
inline void Ins::clear_rsp() {
  rsp_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::rsp() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.rsp)
  return rsp_;
}
inline void Ins::set_rsp(::google::protobuf::uint64 value) {
  
  rsp_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.rsp)
}

// uint64 rbp = 8;
inline void Ins::clear_rbp() {
  rbp_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::rbp() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.rbp)
  return rbp_;
}
inline void Ins::set_rbp(::google::protobuf::uint64 value) {
  
  rbp_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.rbp)
}

// uint64 rsi = 9;
inline void Ins::clear_rsi() {
  rsi_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::rsi() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.rsi)
  return rsi_;
}
inline void Ins::set_rsi(::google::protobuf::uint64 value) {
  
  rsi_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.rsi)
}

// uint64 rdi = 10;
inline void Ins::clear_rdi() {
  rdi_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::rdi() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.rdi)
  return rdi_;
}
inline void Ins::set_rdi(::google::protobuf::uint64 value) {
  
  rdi_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.rdi)
}

// uint64 r8 = 11;
inline void Ins::clear_r8() {
  r8_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r8() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r8)
  return r8_;
}
inline void Ins::set_r8(::google::protobuf::uint64 value) {
  
  r8_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r8)
}

// uint64 r9 = 12;
inline void Ins::clear_r9() {
  r9_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r9() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r9)
  return r9_;
}
inline void Ins::set_r9(::google::protobuf::uint64 value) {
  
  r9_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r9)
}

// uint64 r10 = 13;
inline void Ins::clear_r10() {
  r10_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r10() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r10)
  return r10_;
}
inline void Ins::set_r10(::google::protobuf::uint64 value) {
  
  r10_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r10)
}

// uint64 r11 = 14;
inline void Ins::clear_r11() {
  r11_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r11() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r11)
  return r11_;
}
inline void Ins::set_r11(::google::protobuf::uint64 value) {
  
  r11_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r11)
}

// uint64 r12 = 15;
inline void Ins::clear_r12() {
  r12_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r12() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r12)
  return r12_;
}
inline void Ins::set_r12(::google::protobuf::uint64 value) {
  
  r12_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r12)
}

// uint64 r13 = 16;
inline void Ins::clear_r13() {
  r13_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r13() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r13)
  return r13_;
}
inline void Ins::set_r13(::google::protobuf::uint64 value) {
  
  r13_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r13)
}

// uint64 r14 = 17;
inline void Ins::clear_r14() {
  r14_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r14() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r14)
  return r14_;
}
inline void Ins::set_r14(::google::protobuf::uint64 value) {
  
  r14_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r14)
}

// uint64 r15 = 18;
inline void Ins::clear_r15() {
  r15_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r15() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r15)
  return r15_;
}
inline void Ins::set_r15(::google::protobuf::uint64 value) {
  
  r15_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r15)
}

// uint64 cc_op = 19;
inline void Ins::clear_cc_op() {
  cc_op_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::cc_op() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.cc_op)
  return cc_op_;
}
inline void Ins::set_cc_op(::google::protobuf::uint64 value) {
  
  cc_op_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.cc_op)
}

// uint64 cc_dep1 = 20;
inline void Ins::clear_cc_dep1() {
  cc_dep1_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::cc_dep1() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.cc_dep1)
  return cc_dep1_;
}
inline void Ins::set_cc_dep1(::google::protobuf::uint64 value) {
  
  cc_dep1_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.cc_dep1)
}

// uint64 cc_dep2 = 21;
inline void Ins::clear_cc_dep2() {
  cc_dep2_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::cc_dep2() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.cc_dep2)
  return cc_dep2_;
}
inline void Ins::set_cc_dep2(::google::protobuf::uint64 value) {
  
  cc_dep2_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.cc_dep2)
}

// uint64 cc_ndep = 22;
inline void Ins::clear_cc_ndep() {
  cc_ndep_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::cc_ndep() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.cc_ndep)
  return cc_ndep_;
}
inline void Ins::set_cc_ndep(::google::protobuf::uint64 value) {
  
  cc_ndep_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.cc_ndep)
}

// uint64 gs = 23;
inline void Ins::clear_gs() {
  gs_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::gs() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.gs)
  return gs_;
}
inline void Ins::set_gs(::google::protobuf::uint64 value) {
  
  gs_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.gs)
}

// uint64 r_184 = 24;
inline void Ins::clear_r_184() {
  r_184_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r_184() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r_184)
  return r_184_;
}
inline void Ins::set_r_184(::google::protobuf::uint64 value) {
  
  r_184_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r_184)
}

// uint64 r_192 = 25;
inline void Ins::clear_r_192() {
  r_192_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r_192() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r_192)
  return r_192_;
}
inline void Ins::set_r_192(::google::protobuf::uint64 value) {
  
  r_192_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r_192)
}

// uint64 r_200 = 26;
inline void Ins::clear_r_200() {
  r_200_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::r_200() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.r_200)
  return r_200_;
}
inline void Ins::set_r_200(::google::protobuf::uint64 value) {
  
  r_200_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.r_200)
}

// uint64 pid = 27;
inline void Ins::clear_pid() {
  pid_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Ins::pid() const {
  // @@protoc_insertion_point(field_get:RawTrace.Ins.pid)
  return pid_;
}
inline void Ins::set_pid(::google::protobuf::uint64 value) {
  
  pid_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Ins.pid)
}

// -------------------------------------------------------------------

// Data

// .RawTrace.DataType type = 1;
inline void Data::clear_type() {
  type_ = 0;
}
inline ::RawTrace::DataType Data::type() const {
  // @@protoc_insertion_point(field_get:RawTrace.Data.type)
  return static_cast< ::RawTrace::DataType >(type_);
}
inline void Data::set_type(::RawTrace::DataType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Data.type)
}

// uint64 value = 2;
inline void Data::clear_value() {
  value_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Data::value() const {
  // @@protoc_insertion_point(field_get:RawTrace.Data.value)
  return value_;
}
inline void Data::set_value(::google::protobuf::uint64 value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Data.value)
}

// -------------------------------------------------------------------

// Sched

// .RawTrace.SchedType type = 1;
inline void Sched::clear_type() {
  type_ = 0;
}
inline ::RawTrace::SchedType Sched::type() const {
  // @@protoc_insertion_point(field_get:RawTrace.Sched.type)
  return static_cast< ::RawTrace::SchedType >(type_);
}
inline void Sched::set_type(::RawTrace::SchedType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Sched.type)
}

// uint32 pid = 2;
inline void Sched::clear_pid() {
  pid_ = 0u;
}
inline ::google::protobuf::uint32 Sched::pid() const {
  // @@protoc_insertion_point(field_get:RawTrace.Sched.pid)
  return pid_;
}
inline void Sched::set_pid(::google::protobuf::uint32 value) {
  
  pid_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Sched.pid)
}

// uint64 target = 3;
inline void Sched::clear_target() {
  target_ = PROTOBUF_ULONGLONG(0);
}
inline ::google::protobuf::uint64 Sched::target() const {
  // @@protoc_insertion_point(field_get:RawTrace.Sched.target)
  return target_;
}
inline void Sched::set_target(::google::protobuf::uint64 value) {
  
  target_ = value;
  // @@protoc_insertion_point(field_set:RawTrace.Sched.target)
}

// -------------------------------------------------------------------

// Record

// .RawTrace.Ins ins = 1;
inline bool Record::has_ins() const {
  return item_case() == kIns;
}
inline void Record::set_has_ins() {
  _oneof_case_[0] = kIns;
}
inline void Record::clear_ins() {
  if (has_ins()) {
    delete item_.ins_;
    clear_has_item();
  }
}
inline ::RawTrace::Ins* Record::release_ins() {
  // @@protoc_insertion_point(field_release:RawTrace.Record.ins)
  if (has_ins()) {
    clear_has_item();
      ::RawTrace::Ins* temp = item_.ins_;
    item_.ins_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::RawTrace::Ins& Record::ins() const {
  // @@protoc_insertion_point(field_get:RawTrace.Record.ins)
  return has_ins()
      ? *item_.ins_
      : *reinterpret_cast< ::RawTrace::Ins*>(&::RawTrace::_Ins_default_instance_);
}
inline ::RawTrace::Ins* Record::mutable_ins() {
  if (!has_ins()) {
    clear_item();
    set_has_ins();
    item_.ins_ = CreateMaybeMessage< ::RawTrace::Ins >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:RawTrace.Record.ins)
  return item_.ins_;
}

// .RawTrace.Mem mem = 2;
inline bool Record::has_mem() const {
  return item_case() == kMem;
}
inline void Record::set_has_mem() {
  _oneof_case_[0] = kMem;
}
inline void Record::clear_mem() {
  if (has_mem()) {
    delete item_.mem_;
    clear_has_item();
  }
}
inline ::RawTrace::Mem* Record::release_mem() {
  // @@protoc_insertion_point(field_release:RawTrace.Record.mem)
  if (has_mem()) {
    clear_has_item();
      ::RawTrace::Mem* temp = item_.mem_;
    item_.mem_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::RawTrace::Mem& Record::mem() const {
  // @@protoc_insertion_point(field_get:RawTrace.Record.mem)
  return has_mem()
      ? *item_.mem_
      : *reinterpret_cast< ::RawTrace::Mem*>(&::RawTrace::_Mem_default_instance_);
}
inline ::RawTrace::Mem* Record::mutable_mem() {
  if (!has_mem()) {
    clear_item();
    set_has_mem();
    item_.mem_ = CreateMaybeMessage< ::RawTrace::Mem >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:RawTrace.Record.mem)
  return item_.mem_;
}

// .RawTrace.Data data = 3;
inline bool Record::has_data() const {
  return item_case() == kData;
}
inline void Record::set_has_data() {
  _oneof_case_[0] = kData;
}
inline void Record::clear_data() {
  if (has_data()) {
    delete item_.data_;
    clear_has_item();
  }
}
inline ::RawTrace::Data* Record::release_data() {
  // @@protoc_insertion_point(field_release:RawTrace.Record.data)
  if (has_data()) {
    clear_has_item();
      ::RawTrace::Data* temp = item_.data_;
    item_.data_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::RawTrace::Data& Record::data() const {
  // @@protoc_insertion_point(field_get:RawTrace.Record.data)
  return has_data()
      ? *item_.data_
      : *reinterpret_cast< ::RawTrace::Data*>(&::RawTrace::_Data_default_instance_);
}
inline ::RawTrace::Data* Record::mutable_data() {
  if (!has_data()) {
    clear_item();
    set_has_data();
    item_.data_ = CreateMaybeMessage< ::RawTrace::Data >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:RawTrace.Record.data)
  return item_.data_;
}

// .RawTrace.Syscall syscall = 4;
inline bool Record::has_syscall() const {
  return item_case() == kSyscall;
}
inline void Record::set_has_syscall() {
  _oneof_case_[0] = kSyscall;
}
inline void Record::clear_syscall() {
  if (has_syscall()) {
    delete item_.syscall_;
    clear_has_item();
  }
}
inline ::RawTrace::Syscall* Record::release_syscall() {
  // @@protoc_insertion_point(field_release:RawTrace.Record.syscall)
  if (has_syscall()) {
    clear_has_item();
      ::RawTrace::Syscall* temp = item_.syscall_;
    item_.syscall_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::RawTrace::Syscall& Record::syscall() const {
  // @@protoc_insertion_point(field_get:RawTrace.Record.syscall)
  return has_syscall()
      ? *item_.syscall_
      : *reinterpret_cast< ::RawTrace::Syscall*>(&::RawTrace::_Syscall_default_instance_);
}
inline ::RawTrace::Syscall* Record::mutable_syscall() {
  if (!has_syscall()) {
    clear_item();
    set_has_syscall();
    item_.syscall_ = CreateMaybeMessage< ::RawTrace::Syscall >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:RawTrace.Record.syscall)
  return item_.syscall_;
}

// .RawTrace.Sched sched = 5;
inline bool Record::has_sched() const {
  return item_case() == kSched;
}
inline void Record::set_has_sched() {
  _oneof_case_[0] = kSched;
}
inline void Record::clear_sched() {
  if (has_sched()) {
    delete item_.sched_;
    clear_has_item();
  }
}
inline ::RawTrace::Sched* Record::release_sched() {
  // @@protoc_insertion_point(field_release:RawTrace.Record.sched)
  if (has_sched()) {
    clear_has_item();
      ::RawTrace::Sched* temp = item_.sched_;
    item_.sched_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::RawTrace::Sched& Record::sched() const {
  // @@protoc_insertion_point(field_get:RawTrace.Record.sched)
  return has_sched()
      ? *item_.sched_
      : *reinterpret_cast< ::RawTrace::Sched*>(&::RawTrace::_Sched_default_instance_);
}
inline ::RawTrace::Sched* Record::mutable_sched() {
  if (!has_sched()) {
    clear_item();
    set_has_sched();
    item_.sched_ = CreateMaybeMessage< ::RawTrace::Sched >(
        GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:RawTrace.Record.sched)
  return item_.sched_;
}

inline bool Record::has_item() const {
  return item_case() != ITEM_NOT_SET;
}
inline void Record::clear_has_item() {
  _oneof_case_[0] = ITEM_NOT_SET;
}
inline Record::ItemCase Record::item_case() const {
  return Record::ItemCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Trace

// repeated .RawTrace.Record records = 1;
inline int Trace::records_size() const {
  return records_.size();
}
inline void Trace::clear_records() {
  records_.Clear();
}
inline ::RawTrace::Record* Trace::mutable_records(int index) {
  // @@protoc_insertion_point(field_mutable:RawTrace.Trace.records)
  return records_.Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::RawTrace::Record >*
Trace::mutable_records() {
  // @@protoc_insertion_point(field_mutable_list:RawTrace.Trace.records)
  return &records_;
}
inline const ::RawTrace::Record& Trace::records(int index) const {
  // @@protoc_insertion_point(field_get:RawTrace.Trace.records)
  return records_.Get(index);
}
inline ::RawTrace::Record* Trace::add_records() {
  // @@protoc_insertion_point(field_add:RawTrace.Trace.records)
  return records_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::RawTrace::Record >&
Trace::records() const {
  // @@protoc_insertion_point(field_list:RawTrace.Trace.records)
  return records_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace RawTrace

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::RawTrace::DataType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RawTrace::DataType>() {
  return ::RawTrace::DataType_descriptor();
}
template <> struct is_proto_enum< ::RawTrace::SchedType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::RawTrace::SchedType>() {
  return ::RawTrace::SchedType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // PROTOBUF_INCLUDED_RawTrace_2eproto
